const { chromium } = require("playwright-core");
(async () => { let page, b;
  b = await chromium.launch({ executablePath: process.env.HOME + "/.cache/ms-playwright/chromium-1117/chrome-linux/chrome", args: ["--no-sandbox"] });
  const ctx = await b.newContext({ viewport: { width: 402, height: 860 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
  page = await ctx.newPage();
  const errs = []; page.on("pageerror", e => errs.push(String(e)));
  await page.goto("https://ecoproof-ai.vercel.app/", { waitUntil: "networkidle" });
  const uid = await page.evaluate(() => localStorage.getItem("ecoproof-user"));
  await page.goto("https://ecoproof-ai.vercel.app/map?place=demo-0", { waitUntil: "networkidle" });
  await page.waitForSelector("text=SuperBee Eco Shop"); await page.waitForTimeout(1500);
  await page.screenshot({ path: "/tmp/claude-1000/-home-pola-Development-EcoProofAi/aa6765ce-3c72-45ca-b613-da7cecdc505d/scratchpad/r1-sheet.png" });
  await page.click("text=Review with receipt");
  await page.click('button[aria-label="5 stars"]');
  await page.check("text=No plastic straws >> input").catch(async()=>{ await page.locator('label:has-text("No plastic straws") input').check(); });
  await page.locator('label:has-text("brought my own cup") input').check();
  await page.click("text=Use a fresh demo receipt");
  await page.waitForSelector("text=demo-receipt.png");
  await page.screenshot({ path: "/tmp/claude-1000/-home-pola-Development-EcoProofAi/aa6765ce-3c72-45ca-b613-da7cecdc505d/scratchpad/r2-form.png" });
  console.log("file label:", (await page.innerText("body")).match(/📎[^\n]*|Add your receipt photo/)?.[0]);
  await page.click("text=Submit review");
  await page.waitForSelector("text=Review verified and saved, text=claimed", { timeout: 90000 }).catch(()=>{});
  await page.waitForTimeout(1200);
  const t1 = await page.innerText("body");
  console.log("REVIEW #1:", /Review verified and saved/.test(t1) ? "OK" : "FAIL", "| anchored:", /Review anchored on Solana/.test(t1), "| claimed:", /Receipt claimed on Solana/.test(t1), "| streak msg:", /Bring-your-own-cup counted/.test(t1));
  await page.screenshot({ path: "/tmp/claude-1000/-home-pola-Development-EcoProofAi/aa6765ce-3c72-45ca-b613-da7cecdc505d/scratchpad/r3-done.png" });
  console.log("BODY after submit:", t1.replace(/\n+/g," | ").slice(-700));
  await page.click("text=Try submitting the same receipt again", { timeout: 8000 }).catch(e=>console.log("retry click failed"));
  await page.waitForSelector("text=already been claimed", { timeout: 90000 }).catch(()=>{});
  const t2 = await page.innerText("body");
  console.log("REVIEW #2 same receipt:", /already been claimed/.test(t2) ? "REJECTED (correct)" : "NOT REJECTED (bug)");
  await page.screenshot({ path: "/tmp/claude-1000/-home-pola-Development-EcoProofAi/aa6765ce-3c72-45ca-b613-da7cecdc505d/scratchpad/r4-reject.png" });
  console.log("userId:", uid, "| page errors:", JSON.stringify(errs));
  await b.close();
})();
