import type { Category } from "./impact";
import products from "../data/superbee-products.json";

// SuperBee's real range, mapped by hand to impact categories. The shop sells in English and Thai (every product has two ids), so
// there are two layers: an exact map by WooCommerce product id (data/superbee-products.json, generated by
// scripts/superbee-catalogue.ts from the shop's public product list) and name rules (English + Thai) for anything newer.
// A bundle is several products: [[category, count], ...]. Estimates stay deliberately conservative (a DIY kit counts once).

export type Part = [Category, number];
type Rule = { re: RegExp; parts: Part[] };

const B = { // bundle contents, from the product pages
  laundryKit: [["plastic_free_laundry", 1], ["natural_cleaning_tool", 1], ["reusable_bag", 1]] as Part[], // Hexawash + wool dryer balls + mesh bags
  oralKit: [["plastic_free_oral_care", 3], ["beeswax_wrap", 1]] as Part[], // bamboo toothbrush + floss + toothpaste tabs, beeswax bag
  giftBasket: [["reusable_household_textile", 1], ["natural_cleaning_tool", 2], ["beeswax_wrap", 2], ["reusable_cup", 1], ["plastic_free_laundry", 1], ["reusable_bag", 1]] as Part[], // kitchen roll, 2 loofah, wrap set + food bag, bamboo mug, Hexawash, 5 mesh bags
};

/** First match wins, so specific products and bundles come before the generic words. */
export const RULES: Rule[] = [
  { re: /ocean action bundle|hexagonia bundle|ชุดของขวัญ/i, parts: B.giftBasket },
  { re: /laundry kit|ชุดซักผ้า/i, parts: B.laundryKit },
  { re: /oral care eco-travel kit|ชุดดูแลช่องปาก/i, parts: B.oralKit },
  { re: /by meter|ตามขนาดเมตร|fire ?starter/i, parts: [] }, // raw cotton by the metre, fire starters: not counted
  { re: /diy|beeswax bar|wrap drops|หยดขี้ผึ้ง|ขี้ผึ้งขูด/i, parts: [["beeswax_wrap", 1]] }, // one DIY kit counts as one wrap (it makes 6 to 10)
  { re: /soap bar|สบู่/i, parts: [["refill_cleaning", 1]] },
  { re: /hexawash|laundry detergent|ผงซักฟอก/i, parts: [["plastic_free_laundry", 1]] },
  { re: /toothbrush|toothpaste|tooth tab|tabs|floss|dentos|แปรงสีฟัน|ยาสีฟัน|ทูธเพสต์|ไหมขัดฟัน/i, parts: [["plastic_free_oral_care", 1]] },
  { re: /straw|หลอด/i, parts: [["reusable_straw_cutlery", 1]] },
  { re: /dryer ball|luffa|loofah|ลูกบอลอบผ้า|ใยขัด/i, parts: [["natural_cleaning_tool", 1]] },
  { re: /kitchen roll|cotton rounds|กระดาษเช็ดมือ|ผ้าฝ้ายออร์แกนิกแบบใช้ซ้ำ/i, parts: [["reusable_household_textile", 1]] },
  { re: /mesh|tote|ถุงตาข่าย|โท้ท/i, parts: [["reusable_bag", 1]] },
  { re: /beeswax|wax|wrap|bread|lunch bag|food bag|ขี้ผึ้ง|ไขผึ้ง|แว็กซ์|ถุงอาหาร|ถุงใส่ข้าว|ขนมปัง|ห่อ/i, parts: [["beeswax_wrap", 1]] },
];

export const classify = (name: string): Part[] | null => RULES.find((r) => r.re.test(name))?.parts ?? null;

const BY_ID = products as unknown as Record<string, { name: string; parts: Part[] }>;

/** What a SuperBee order line contains: by product id when we know it, otherwise by name. null = unknown (the AI decides). */
export function superbeeParts(productId: number | undefined, name: string): Part[] | null {
  const hit = productId != null ? BY_ID[String(productId)] : undefined;
  return hit ? hit.parts : classify(name);
}
